import { z } from "zod";

export const empresaSchema = z.object({
  nome: z.string().min(1, "Nome é obrigatório"),
  cnpj: z.string().optional(),
  razaoSocial: z.string().optional(),
  nomeFantasia: z.string().optional(),
  situacaoCadastral: z.string().optional(),
  dataSituacaoCadastral: z.date().optional().or(z.string().optional()),
  matrizFilial: z.string().optional(),
  dataInicioAtividade: z.date().optional().or(z.string().optional()),
  cnaePrincipal: z.string().optional(),
  cnaesSecundarios: z.string().optional(),
  naturezaJuridica: z.string().optional(),
  logradouro: z.string().optional(),
  numero: z.string().optional(),
  complemento: z.string().optional(),
  bairro: z.string().optional(),
  cep: z.string().optional(),
  uf: z.string().optional(),
  municipio: z.string().optional(),
  email: z.string().email("Email inválido").optional().or(z.literal("")),
  telefone: z.string().optional(),
  telefones: z.string().optional(),
  capitalSocial: z.string().optional(),
  porteEmpresa: z.string().optional(),
  opcaoSimples: z.string().optional(),
  dataOpcaoSimples: z.date().optional().or(z.string().optional()),
  opcaoMei: z.string().optional(),
  dataOpcaoMei: z.date().optional().or(z.string().optional()),
  qsa: z.string().optional(),
  ativa: z.boolean().default(true),
  dataInicio: z.string().optional(),
  dataFim: z.string().optional(),
  observacoes: z.string().optional(),
});

export type EmpresaFormData = z.infer<typeof empresaSchema>;
